# Importing super.csv file:

In [5]:
import pandas as pd
data1=pd.read_csv("C://Users//Tanuja//Desktop//DATA-SET//super.csv")
data1

,order_id,customer_id,order_date,customer_name,state,category,sub_category,sales,Review
0,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.9600,Good
1,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Chairs,731.9400,Good
2,CA-2016-138688,DV-13045,06-12-2016,Darrin Van Huff,California,Office Supplies,Labels,14.6200,Good
3,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Furniture,Tables,957.5775,Bad
4,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Office Supplies,Storage,22.3680,Bad
5,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Furnishings,48.8600,Good
6,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Art,7.2800,Bad
7,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,907.1520,Bad
8,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Binders,18.5040,Good
9,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Appliances,114.9000,Good
10,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Tables,1706.1840,Bad
11,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,911.4240,Bad
12,CA-2017-114412,AA-10480,4/15/2017,Andrew Allen,North Carolina,Office Supplies,Paper,15.5520,Good
13,CA-2016-161389,IM-15070,12-05-2016,Irene Maddox,Washington,Office Supplies,Binders,407.9760,Bad
14,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Appliances,68.8100,Good
15,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Binders,2.5440,Good
16,CA-2014-105893,PK-19075,11-11-2014,Pete Kriz,Wisconsin,Office Supplies,Storage,665.8800,Bad
17,CA-2014-167164,AG-10270,5/13/2014,Alejandro Grove,Utah,Office Supplies,Storage,55.5000,Bad
18,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Art,8.5600,Good
19,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Technology,Phones,213.4800,Bad
20,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.7200,Bad

In [8]:
new_duplicated=data1[data1.duplicated('customer_id')]
new_duplicated

,order_id,customer_id,order_date,customer_name,state,category,sub_category,sales,Review
1,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Chairs,731.940,Good
4,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Office Supplies,Storage,22.368,Bad
6,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Art,7.280,Bad
7,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,907.152,Bad
8,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Binders,18.504,Good
9,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Appliances,114.900,Good
10,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Tables,1706.184,Bad
11,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,911.424,Bad
15,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Binders,2.544,Good
19,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Technology,Phones,213.480,Bad
20,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.720,Bad

# Importing products.csv file:

In [6]:
import pandas as pd
data2=pd.read_csv("C://Users//Tanuja//Desktop//DATA-SET//products.csv")
data2

,Index,Product_name,Product_price,Product_rating,Review
0,0,"REDMI 9i Sport (Coral Green, 64 GB)","₹8,799",4.4,Good
1,1,"realme Narzo 50A (Oxygen Blue, 64 GB)","₹11,499",4.4,Good
2,2,"realme 8i (Space Black, 128 GB)","₹15,999",4.4,Good
3,3,"realme 8i (Space Black, 64 GB)","₹13,999",4.5,Bad
4,4,"realme Narzo 50A (Oxygen Green, 64 GB)","₹11,499",4.4,Bad
5,5,"realme Narzo 50A (Oxygen Blue, 128 GB)","₹12,499",4.4,Good
6,6,"REDMI 9i Sport (Metallic Blue, 64 GB)","₹8,799",4.4,Bad
7,7,"REDMI 9i Sport (Carbon Black, 64 GB)","₹8,799",4.4,Bad
8,8,"APPLE iPhone SE (Red, 64 GB)","₹27,999",4.5,Good
9,9,"POCO C31 (Shadow Gray, 64 GB)","₹8,999",4.4,Bad
10,10,"realme C21Y (Cross Black, 32 GB)","₹9,499",4.6,Bad
11,11,"realme C21Y (Cross Black, 64 GB)","₹10,499",4.5,Bad
12,12,"realme C21Y (Cross Blue, 64 GB)","₹10,499",4.5,Good
13,13,"POCO C31 (Royal Blue, 32 GB)","₹7,999",4.4,Bad
14,14,"realme C21Y (Cross Blue, 32 GB)","₹9,499",4.6,Good
15,15,"APPLE iPhone 12 Mini (Black, 64 GB)","₹38,999",4.5,Good
16,16,"MOTOROLA g31 (Baby Blue, 64 GB)","₹12,999",4.3,Bad
17,17,"APPLE iPhone SE (White, 64 GB)","₹27,999",4.5,Bad
18,18,"MOTOROLA g31 (Meteorite Grey, 64 GB)","₹12,999",4.3,Good
19,19,"realme 8 (Cyber Black, 128 GB)","₹16,999",4.4,Bad
20,20,"realme 8 (Cyber Silver, 128 GB)","₹17,999",4.4,Bad
21,21,"realme C11 2021 (Cool Grey, 32 GB)","₹7,499",4.4,Good
22,22,"realme C11 2021 (Cool Grey, 64 GB)","₹8,999",4.3,Bad
23,23,"realme C11 2021 (Cool Blue, 64 GB)","₹8,999",4.3,Good

In [7]:
# droping the column name:

import pandas as pd
data2=pd.read_csv("C://Users//Tanuja//Desktop//DATA-SET//products.csv")
data2=pd.DataFrame(data2)
data2.drop(["Index"],axis=1)

,Product_name,Product_price,Product_rating,Review
0,"REDMI 9i Sport (Coral Green, 64 GB)","₹8,799",4.4,Good
1,"realme Narzo 50A (Oxygen Blue, 64 GB)","₹11,499",4.4,Good
2,"realme 8i (Space Black, 128 GB)","₹15,999",4.4,Good
3,"realme 8i (Space Black, 64 GB)","₹13,999",4.5,Bad
4,"realme Narzo 50A (Oxygen Green, 64 GB)","₹11,499",4.4,Bad
5,"realme Narzo 50A (Oxygen Blue, 128 GB)","₹12,499",4.4,Good
6,"REDMI 9i Sport (Metallic Blue, 64 GB)","₹8,799",4.4,Bad
7,"REDMI 9i Sport (Carbon Black, 64 GB)","₹8,799",4.4,Bad
8,"APPLE iPhone SE (Red, 64 GB)","₹27,999",4.5,Good
9,"POCO C31 (Shadow Gray, 64 GB)","₹8,999",4.4,Bad
10,"realme C21Y (Cross Black, 32 GB)","₹9,499",4.6,Bad
11,"realme C21Y (Cross Black, 64 GB)","₹10,499",4.5,Bad
12,"realme C21Y (Cross Blue, 64 GB)","₹10,499",4.5,Good
13,"POCO C31 (Royal Blue, 32 GB)","₹7,999",4.4,Bad
14,"realme C21Y (Cross Blue, 32 GB)","₹9,499",4.6,Good
15,"APPLE iPhone 12 Mini (Black, 64 GB)","₹38,999",4.5,Good
16,"MOTOROLA g31 (Baby Blue, 64 GB)","₹12,999",4.3,Bad
17,"APPLE iPhone SE (White, 64 GB)","₹27,999",4.5,Bad
18,"MOTOROLA g31 (Meteorite Grey, 64 GB)","₹12,999",4.3,Good
19,"realme 8 (Cyber Black, 128 GB)","₹16,999",4.4,Bad
20,"realme 8 (Cyber Silver, 128 GB)","₹17,999",4.4,Bad
21,"realme C11 2021 (Cool Grey, 32 GB)","₹7,499",4.4,Good
22,"realme C11 2021 (Cool Grey, 64 GB)","₹8,999",4.3,Bad
23,"realme C11 2021 (Cool Blue, 64 GB)","₹8,999",4.3,Good

# Pandas DataFrame.append():

In [8]:
#append data2 in data1

data1=pd.read_csv("C://Users//Tanuja//Desktop//DATA-SET//super.csv")
data1.append(data2,ignore_index=True)

,order_id,customer_id,order_date,customer_name,state,category,sub_category,sales,Review,Index,Product_name,Product_price,Product_rating
0,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.9600,Good,NaN,NaN,NaN,NaN
1,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Chairs,731.9400,Good,NaN,NaN,NaN,NaN
2,CA-2016-138688,DV-13045,06-12-2016,Darrin Van Huff,California,Office Supplies,Labels,14.6200,Good,NaN,NaN,NaN,NaN
3,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Furniture,Tables,957.5775,Bad,NaN,NaN,NaN,NaN
4,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Office Supplies,Storage,22.3680,Bad,NaN,NaN,NaN,NaN
5,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Furnishings,48.8600,Good,NaN,NaN,NaN,NaN
6,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Art,7.2800,Bad,NaN,NaN,NaN,NaN
7,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,907.1520,Bad,NaN,NaN,NaN,NaN
8,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Binders,18.5040,Good,NaN,NaN,NaN,NaN
9,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Appliances,114.9000,Good,NaN,NaN,NaN,NaN
10,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Tables,1706.1840,Bad,NaN,NaN,NaN,NaN
11,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,911.4240,Bad,NaN,NaN,NaN,NaN
12,CA-2017-114412,AA-10480,4/15/2017,Andrew Allen,North Carolina,Office Supplies,Paper,15.5520,Good,NaN,NaN,NaN,NaN
13,CA-2016-161389,IM-15070,12-05-2016,Irene Maddox,Washington,Office Supplies,Binders,407.9760,Bad,NaN,NaN,NaN,NaN
14,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Appliances,68.8100,Good,NaN,NaN,NaN,NaN
15,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Binders,2.5440,Good,NaN,NaN,NaN,NaN
16,CA-2014-105893,PK-19075,11-11-2014,Pete Kriz,Wisconsin,Office Supplies,Storage,665.8800,Bad,NaN,NaN,NaN,NaN
17,CA-2014-167164,AG-10270,5/13/2014,Alejandro Grove,Utah,Office Supplies,Storage,55.5000,Bad,NaN,NaN,NaN,NaN
18,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Art,8.5600,Good,NaN,NaN,NaN,NaN
19,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Technology,Phones,213.4800,Bad,NaN,NaN,NaN,NaN
20,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.7200,Bad,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,0.0,"REDMI 9i Sport (Coral Green, 64 GB)","₹8,799",4.4
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,1.0,"realme Narzo 50A (Oxygen Blue, 64 GB)","₹11,499",4.4
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,2.0,"realme 8i (Space Black, 128 GB)","₹15,999",4.4
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,3.0,"realme 8i (Space Black, 64 GB)","₹13,999",4.5
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,4.0,"realme Narzo 50A (Oxygen Green, 64 GB)","₹11,499",4.4
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,5.0,"realme Narzo 50A (Oxygen Blue, 128 GB)","₹12,499",4.4
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,6.0,"REDMI 9i Sport (Metallic Blue, 64 GB)","₹8,799",4.4
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,7.0,"REDMI 9i Sport (Carbon Black, 64 GB)","₹8,799",4.4
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,8.0,"APPLE iPhone SE (Red, 64 GB)","₹27,999",4.5
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,9.0,"POCO C31 (Shadow Gray, 64 GB)","₹8,999",4.4
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,10.0,"realme C21Y (Cross Black, 32 GB)","₹9,499",4.6
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,11.0,"realme C21Y (Cross Black, 64 GB)","₹10,499",4.5
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,12.0,"realme C21Y (Cross Blue, 64 GB)","₹10,499",4.5
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,13.0,"POCO C31 (Royal Blue, 32 GB)","₹7,999",4.4
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,14.0,"realme C21Y (Cross Blue, 32 GB)","₹9,499",4.6
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,15.0,"APPLE iPhone 12 Mini (Black, 64 GB)","₹38,999",4.5
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,16.0,"MOTOROLA g31 (Baby Blue, 64 GB)","₹12,999",4.3
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,17.0,"APPLE iPhone SE (White, 64 GB)","₹27,999",4.5
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,18.0,"MOTOROLA g31 (Meteorite Grey, 64 GB)","₹12,999",4.3
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,19.0,"realme 8 (Cyber Black, 128 GB)","₹16,999",4.4
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,20.0,"realme 8 (Cyber Silver, 128 GB)","₹17,999",4.4
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,21.0,"realme C11 2021 (Cool Grey, 32 GB)","₹7,499",4.4
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,22.0,"realme C11 2021 (Cool Grey, 64 GB)","₹8,999",4.3
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,23.0,"realme C11 2021 (Cool Blue, 64 GB)","₹8,999",4.3

In [9]:
# append data1 in data2

data1=pd.read_csv("C://Users//Tanuja//Desktop//DATA-SET//super.csv")
data2.append(data1,ignore_index=True)

,Index,Product_name,Product_price,Product_rating,Review,order_id,customer_id,order_date,customer_name,state,category,sub_category,sales
0,0.0,"REDMI 9i Sport (Coral Green, 64 GB)","₹8,799",4.4,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,"realme Narzo 50A (Oxygen Blue, 64 GB)","₹11,499",4.4,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,"realme 8i (Space Black, 128 GB)","₹15,999",4.4,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,"realme 8i (Space Black, 64 GB)","₹13,999",4.5,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,"realme Narzo 50A (Oxygen Green, 64 GB)","₹11,499",4.4,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5.0,"realme Narzo 50A (Oxygen Blue, 128 GB)","₹12,499",4.4,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6.0,"REDMI 9i Sport (Metallic Blue, 64 GB)","₹8,799",4.4,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7.0,"REDMI 9i Sport (Carbon Black, 64 GB)","₹8,799",4.4,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8.0,"APPLE iPhone SE (Red, 64 GB)","₹27,999",4.5,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9.0,"POCO C31 (Shadow Gray, 64 GB)","₹8,999",4.4,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10.0,"realme C21Y (Cross Black, 32 GB)","₹9,499",4.6,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11.0,"realme C21Y (Cross Black, 64 GB)","₹10,499",4.5,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12.0,"realme C21Y (Cross Blue, 64 GB)","₹10,499",4.5,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13.0,"POCO C31 (Royal Blue, 32 GB)","₹7,999",4.4,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14.0,"realme C21Y (Cross Blue, 32 GB)","₹9,499",4.6,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15.0,"APPLE iPhone 12 Mini (Black, 64 GB)","₹38,999",4.5,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16.0,"MOTOROLA g31 (Baby Blue, 64 GB)","₹12,999",4.3,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17.0,"APPLE iPhone SE (White, 64 GB)","₹27,999",4.5,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18.0,"MOTOROLA g31 (Meteorite Grey, 64 GB)","₹12,999",4.3,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19.0,"realme 8 (Cyber Black, 128 GB)","₹16,999",4.4,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20.0,"realme 8 (Cyber Silver, 128 GB)","₹17,999",4.4,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21.0,"realme C11 2021 (Cool Grey, 32 GB)","₹7,499",4.4,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22.0,"realme C11 2021 (Cool Grey, 64 GB)","₹8,999",4.3,Bad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23.0,"realme C11 2021 (Cool Blue, 64 GB)","₹8,999",4.3,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,Good,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.9600
25,NaN,NaN,NaN,NaN,Good,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Chairs,731.9400
26,NaN,NaN,NaN,NaN,Good,CA-2016-138688,DV-13045,06-12-2016,Darrin Van Huff,California,Office Supplies,Labels,14.6200
27,NaN,NaN,NaN,NaN,Bad,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Furniture,Tables,957.5775
28,NaN,NaN,NaN,NaN,Bad,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Office Supplies,Storage,22.3680
29,NaN,NaN,NaN,NaN,Good,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Furnishings,48.8600
30,NaN,NaN,NaN,NaN,Bad,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Art,7.2800
31,NaN,NaN,NaN,NaN,Bad,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,907.1520
32,NaN,NaN,NaN,NaN,Good,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Binders,18.5040
33,NaN,NaN,NaN,NaN,Good,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Appliances,114.9000
34,NaN,NaN,NaN,NaN,Bad,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Tables,1706.1840
35,NaN,NaN,NaN,NaN,Bad,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,911.4240
36,NaN,NaN,NaN,NaN,Good,CA-2017-114412,AA-10480,4/15/2017,Andrew Allen,North Carolina,Office Supplies,Paper,15.5520
37,NaN,NaN,NaN,NaN,Bad,CA-2016-161389,IM-15070,12-05-2016,Irene Maddox,Washington,Office Supplies,Binders,407.9760
38,NaN,NaN,NaN,NaN,Good,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Appliances,68.8100
39,NaN,NaN,NaN,NaN,Good,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Binders,2.5440
40,NaN,NaN,NaN,NaN,Bad,CA-2014-105893,PK-19075,11-11-2014,Pete Kriz,Wisconsin,Office Supplies,Storage,665.8800
41,NaN,NaN,NaN,NaN,Bad,CA-2014-167164,AG-10270,5/13/2014,Alejandro Grove,Utah,Office Supplies,Storage,55.5000
42,NaN,NaN,NaN,NaN,Good,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Art,8.5600
43,NaN,NaN,NaN,NaN,Bad,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Technology,Phones,213.4800
44,NaN,NaN,NaN,NaN,Bad,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.7200

# Pandas DataFrame.describe():

In [10]:
data1.describe()

             sales
count    21.000000
mean    341.132929
std     464.917033
min       2.544000
25%      18.504000
50%      68.810000
75%     665.880000
max    1706.184000

In [11]:
data2.describe()

           Index  Product_rating
count  24.000000       24.000000
mean   11.500000        4.425000
std     7.071068        0.084699
min     0.000000        4.300000
25%     5.750000        4.400000
50%    11.500000        4.400000
75%    17.250000        4.500000
max    23.000000        4.600000

In [12]:
# info

data1.info()
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       21 non-null     object
 1   customer_id    21 non-null     object
 2   order_date     21 non-null     object
 3   customer_name  21 non-null     object
 4   state          21 non-null     object
 5   category       21 non-null     object
 6   sub_category   21 non-null     object
 7   sales          21 non-null     float64
 8   Review         21 non-null     object
dtypes: float64(1), object(8)
memory usage: 1.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Index           24 non-null     int64
 1   Product_name    24 non-null     object
 2   Product_price   24 non-null     object
 3   Product_rating  24 non-null     float64
 4   Review          24 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 1.1+ KB

# Data Wrangling:

In [47]:
# merging the data:

pd.merge(data1,data2,on="Review")

,order_id,customer_id,order_date,customer_name,state,category,sub_category,sales,Review,Index,Product_name,Product_price,Product_rating
0,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.960,Good,0,"REDMI 9i Sport (Coral Green, 64 GB)","₹8,799",4.4
1,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.960,Good,1,"realme Narzo 50A (Oxygen Blue, 64 GB)","₹11,499",4.4
2,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.960,Good,2,"realme 8i (Space Black, 128 GB)","₹15,999",4.4
3,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.960,Good,5,"realme Narzo 50A (Oxygen Blue, 128 GB)","₹12,499",4.4
4,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.960,Good,8,"APPLE iPhone SE (Red, 64 GB)","₹27,999",4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.720,Bad,17,"APPLE iPhone SE (White, 64 GB)","₹27,999",4.5
227,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.720,Bad,19,"realme 8 (Cyber Black, 128 GB)","₹16,999",4.4
228,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.720,Bad,20,"realme 8 (Cyber Silver, 128 GB)","₹17,999",4.4
229,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.720,Bad,22,"realme C11 2021 (Cool Grey, 64 GB)","₹8,999",4.3
230,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Tables,1706.184,Bad,10,"realme C21Y (Cross Black, 32 GB)","₹9,499",4.6

# Re-shaping data:

In [35]:
# in the review column we can re-shape the data by categories into numbers Good=1,Bad=0

# Catergories Review data1:

import pandas as  pd
data1=pd.read_csv("C://Users//Tanuja//Desktop//DATA-SET//super.csv")
data1["Review"]=data1["Review"].map({"Good":1,"Bad":0}).astype(float)
data1

,order_id,customer_id,order_date,customer_name,state,category,sub_category,sales,Review
0,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.9600,1.0
1,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Chairs,731.9400,1.0
2,CA-2016-138688,DV-13045,06-12-2016,Darrin Van Huff,California,Office Supplies,Labels,14.6200,1.0
3,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Furniture,Tables,957.5775,0.0
4,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Office Supplies,Storage,22.3680,0.0
5,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Furnishings,48.8600,1.0
6,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Art,7.2800,0.0
7,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,907.1520,0.0
8,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Binders,18.5040,1.0
9,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Appliances,114.9000,1.0
10,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Tables,1706.1840,NaN
11,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,911.4240,0.0
12,CA-2017-114412,AA-10480,4/15/2017,Andrew Allen,North Carolina,Office Supplies,Paper,15.5520,1.0
13,CA-2016-161389,IM-15070,12-05-2016,Irene Maddox,Washington,Office Supplies,Binders,407.9760,0.0
14,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Appliances,68.8100,1.0
15,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Binders,2.5440,1.0
16,CA-2014-105893,PK-19075,11-11-2014,Pete Kriz,Wisconsin,Office Supplies,Storage,665.8800,0.0
17,CA-2014-167164,AG-10270,5/13/2014,Alejandro Grove,Utah,Office Supplies,Storage,55.5000,0.0
18,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Art,8.5600,1.0
19,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Technology,Phones,213.4800,0.0
20,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.7200,0.0

In [37]:
#Finding the mean of the column having NaN

mean_value=data1["Review"].mean()
# Replace NaNs in column age with the
# mean of values in the same column

data1["Review"].fillna(value=mean_value, inplace=True)
print("Updated Dataframe:")
data1

Updated Dataframe:

,order_id,customer_id,order_date,customer_name,state,category,sub_category,sales,Review
0,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.9600,1.0
1,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Chairs,731.9400,1.0
2,CA-2016-138688,DV-13045,06-12-2016,Darrin Van Huff,California,Office Supplies,Labels,14.6200,1.0
3,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Furniture,Tables,957.5775,0.0
4,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Office Supplies,Storage,22.3680,0.0
5,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Furnishings,48.8600,1.0
6,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Art,7.2800,0.0
7,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,907.1520,0.0
8,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Binders,18.5040,1.0
9,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Appliances,114.9000,1.0
10,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Tables,1706.1840,0.5
11,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,911.4240,0.0
12,CA-2017-114412,AA-10480,4/15/2017,Andrew Allen,North Carolina,Office Supplies,Paper,15.5520,1.0
13,CA-2016-161389,IM-15070,12-05-2016,Irene Maddox,Washington,Office Supplies,Binders,407.9760,0.0
14,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Appliances,68.8100,1.0
15,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Binders,2.5440,1.0
16,CA-2014-105893,PK-19075,11-11-2014,Pete Kriz,Wisconsin,Office Supplies,Storage,665.8800,0.0
17,CA-2014-167164,AG-10270,5/13/2014,Alejandro Grove,Utah,Office Supplies,Storage,55.5000,0.0
18,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Art,8.5600,1.0
19,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Technology,Phones,213.4800,0.0
20,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.7200,0.0

In [33]:
# in the review column we can re-shape the data by categories into numbers Good=1,Bad=0

# Catergories Review data2:

import pandas as  pd
data2=pd.read_csv("C://Users//Tanuja//Desktop//DATA-SET//products.csv")
data2["Review"]=data2["Review"].map({"Good":1,"Bad":0}).astype(float)
data2

,Index,Product_name,Product_price,Product_rating,Review
0,0,"REDMI 9i Sport (Coral Green, 64 GB)","₹8,799",4.4,1.0
1,1,"realme Narzo 50A (Oxygen Blue, 64 GB)","₹11,499",4.4,1.0
2,2,"realme 8i (Space Black, 128 GB)","₹15,999",4.4,1.0
3,3,"realme 8i (Space Black, 64 GB)","₹13,999",4.5,0.0
4,4,"realme Narzo 50A (Oxygen Green, 64 GB)","₹11,499",4.4,0.0
5,5,"realme Narzo 50A (Oxygen Blue, 128 GB)","₹12,499",4.4,1.0
6,6,"REDMI 9i Sport (Metallic Blue, 64 GB)","₹8,799",4.4,0.0
7,7,"REDMI 9i Sport (Carbon Black, 64 GB)","₹8,799",4.4,0.0
8,8,"APPLE iPhone SE (Red, 64 GB)","₹27,999",4.5,1.0
9,9,"POCO C31 (Shadow Gray, 64 GB)","₹8,999",4.4,0.0
10,10,"realme C21Y (Cross Black, 32 GB)","₹9,499",4.6,NaN
11,11,"realme C21Y (Cross Black, 64 GB)","₹10,499",4.5,0.0
12,12,"realme C21Y (Cross Blue, 64 GB)","₹10,499",4.5,1.0
13,13,"POCO C31 (Royal Blue, 32 GB)","₹7,999",4.4,0.0
14,14,"realme C21Y (Cross Blue, 32 GB)","₹9,499",4.6,1.0
15,15,"APPLE iPhone 12 Mini (Black, 64 GB)","₹38,999",4.5,1.0
16,16,"MOTOROLA g31 (Baby Blue, 64 GB)","₹12,999",4.3,0.0
17,17,"APPLE iPhone SE (White, 64 GB)","₹27,999",4.5,0.0
18,18,"MOTOROLA g31 (Meteorite Grey, 64 GB)","₹12,999",4.3,1.0
19,19,"realme 8 (Cyber Black, 128 GB)","₹16,999",4.4,0.0
20,20,"realme 8 (Cyber Silver, 128 GB)","₹17,999",4.4,0.0
21,21,"realme C11 2021 (Cool Grey, 32 GB)","₹7,499",4.4,1.0
22,22,"realme C11 2021 (Cool Grey, 64 GB)","₹8,999",4.3,0.0
23,23,"realme C11 2021 (Cool Blue, 64 GB)","₹8,999",4.3,1.0

In [38]:
#Finding the mean of the column having NaN

mean_value=data2["Review"].mean()
# Replace NaNs in column age with the
# mean of values in the same column

data2["Review"].fillna(value=mean_value, inplace=True)
print("Updated Dataframe:")
data2

Updated Dataframe:

,Index,Product_name,Product_price,Product_rating,Review
0,0,"REDMI 9i Sport (Coral Green, 64 GB)","₹8,799",4.4,1.000000
1,1,"realme Narzo 50A (Oxygen Blue, 64 GB)","₹11,499",4.4,1.000000
2,2,"realme 8i (Space Black, 128 GB)","₹15,999",4.4,1.000000
3,3,"realme 8i (Space Black, 64 GB)","₹13,999",4.5,0.000000
4,4,"realme Narzo 50A (Oxygen Green, 64 GB)","₹11,499",4.4,0.000000
5,5,"realme Narzo 50A (Oxygen Blue, 128 GB)","₹12,499",4.4,1.000000
6,6,"REDMI 9i Sport (Metallic Blue, 64 GB)","₹8,799",4.4,0.000000
7,7,"REDMI 9i Sport (Carbon Black, 64 GB)","₹8,799",4.4,0.000000
8,8,"APPLE iPhone SE (Red, 64 GB)","₹27,999",4.5,1.000000
9,9,"POCO C31 (Shadow Gray, 64 GB)","₹8,999",4.4,0.000000
10,10,"realme C21Y (Cross Black, 32 GB)","₹9,499",4.6,0.478261
11,11,"realme C21Y (Cross Black, 64 GB)","₹10,499",4.5,0.000000
12,12,"realme C21Y (Cross Blue, 64 GB)","₹10,499",4.5,1.000000
13,13,"POCO C31 (Royal Blue, 32 GB)","₹7,999",4.4,0.000000
14,14,"realme C21Y (Cross Blue, 32 GB)","₹9,499",4.6,1.000000
15,15,"APPLE iPhone 12 Mini (Black, 64 GB)","₹38,999",4.5,1.000000
16,16,"MOTOROLA g31 (Baby Blue, 64 GB)","₹12,999",4.3,0.000000
17,17,"APPLE iPhone SE (White, 64 GB)","₹27,999",4.5,0.000000
18,18,"MOTOROLA g31 (Meteorite Grey, 64 GB)","₹12,999",4.3,1.000000
19,19,"realme 8 (Cyber Black, 128 GB)","₹16,999",4.4,0.000000
20,20,"realme 8 (Cyber Silver, 128 GB)","₹17,999",4.4,0.000000
21,21,"realme C11 2021 (Cool Grey, 32 GB)","₹7,499",4.4,1.000000
22,22,"realme C11 2021 (Cool Grey, 64 GB)","₹8,999",4.3,0.000000
23,23,"realme C11 2021 (Cool Blue, 64 GB)","₹8,999",4.3,1.000000

# Groupby() method:

In [43]:
# group it by using "groupby() in data1"


grouped=data1.groupby("state")
grouped.get_group("California")

,order_id,customer_id,order_date,customer_name,state,category,sub_category,sales,Review
2,CA-2016-138688,DV-13045,06-12-2016,Darrin Van Huff,California,Office Supplies,Labels,14.620,1.0
5,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Furnishings,48.860,1.0
6,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Art,7.280,0.0
7,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,907.152,0.0
8,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Binders,18.504,1.0
9,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Appliances,114.900,1.0
10,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Tables,1706.184,0.5
11,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,911.424,0.0
18,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Art,8.560,1.0
19,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Technology,Phones,213.480,0.0
20,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.720,0.0

In [42]:
# group it by using "groupby() in data2"


grouped=data2.groupby("Product_rating")
grouped.get_group(4.4)

,Index,Product_name,Product_price,Product_rating,Review
0,0,"REDMI 9i Sport (Coral Green, 64 GB)","₹8,799",4.4,1.0
1,1,"realme Narzo 50A (Oxygen Blue, 64 GB)","₹11,499",4.4,1.0
2,2,"realme 8i (Space Black, 128 GB)","₹15,999",4.4,1.0
4,4,"realme Narzo 50A (Oxygen Green, 64 GB)","₹11,499",4.4,0.0
5,5,"realme Narzo 50A (Oxygen Blue, 128 GB)","₹12,499",4.4,1.0
6,6,"REDMI 9i Sport (Metallic Blue, 64 GB)","₹8,799",4.4,0.0
7,7,"REDMI 9i Sport (Carbon Black, 64 GB)","₹8,799",4.4,0.0
9,9,"POCO C31 (Shadow Gray, 64 GB)","₹8,999",4.4,0.0
13,13,"POCO C31 (Royal Blue, 32 GB)","₹7,999",4.4,0.0
19,19,"realme 8 (Cyber Black, 128 GB)","₹16,999",4.4,0.0
20,20,"realme 8 (Cyber Silver, 128 GB)","₹17,999",4.4,0.0
21,21,"realme C11 2021 (Cool Grey, 32 GB)","₹7,499",4.4,1.0

# Concatenating Data:

In [30]:
pd.concat([data1,data2])

,order_id,customer_id,order_date,customer_name,state,category,sub_category,sales,Review,Index,Product_name,Product_price,Product_rating
0,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Bookcases,261.9600,1.0,NaN,NaN,NaN,NaN
1,CA-2016-152156,CG-12520,11-08-2016,Claire Gute,Kentucky,Furniture,Chairs,731.9400,1.0,NaN,NaN,NaN,NaN
2,CA-2016-138688,DV-13045,06-12-2016,Darrin Van Huff,California,Office Supplies,Labels,14.6200,1.0,NaN,NaN,NaN,NaN
3,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Furniture,Tables,957.5775,0.0,NaN,NaN,NaN,NaN
4,US-2015-108966,SO-20335,10-11-2015,Sean O'Donnell,Florida,Office Supplies,Storage,22.3680,0.0,NaN,NaN,NaN,NaN
5,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Furnishings,48.8600,1.0,NaN,NaN,NaN,NaN
6,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Art,7.2800,0.0,NaN,NaN,NaN,NaN
7,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,907.1520,0.0,NaN,NaN,NaN,NaN
8,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Binders,18.5040,1.0,NaN,NaN,NaN,NaN
9,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Office Supplies,Appliances,114.9000,1.0,NaN,NaN,NaN,NaN
10,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Furniture,Tables,1706.1840,NaN,NaN,NaN,NaN,NaN
11,CA-2014-115812,BH-11710,06-09-2014,Brosina Hoffman,California,Technology,Phones,911.4240,0.0,NaN,NaN,NaN,NaN
12,CA-2017-114412,AA-10480,4/15/2017,Andrew Allen,North Carolina,Office Supplies,Paper,15.5520,1.0,NaN,NaN,NaN,NaN
13,CA-2016-161389,IM-15070,12-05-2016,Irene Maddox,Washington,Office Supplies,Binders,407.9760,0.0,NaN,NaN,NaN,NaN
14,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Appliances,68.8100,1.0,NaN,NaN,NaN,NaN
15,US-2015-118983,HP-14815,11/22/2015,Harold Pawlan,Texas,Office Supplies,Binders,2.5440,1.0,NaN,NaN,NaN,NaN
16,CA-2014-105893,PK-19075,11-11-2014,Pete Kriz,Wisconsin,Office Supplies,Storage,665.8800,0.0,NaN,NaN,NaN,NaN
17,CA-2014-167164,AG-10270,5/13/2014,Alejandro Grove,Utah,Office Supplies,Storage,55.5000,0.0,NaN,NaN,NaN,NaN
18,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Art,8.5600,1.0,NaN,NaN,NaN,NaN
19,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Technology,Phones,213.4800,0.0,NaN,NaN,NaN,NaN
20,CA-2014-143336,ZD-21925,8/27/2014,Zuschuss Donatelli,California,Office Supplies,Binders,22.7200,0.0,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,0.0,"REDMI 9i Sport (Coral Green, 64 GB)","₹8,799",4.4
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,1.0,"realme Narzo 50A (Oxygen Blue, 64 GB)","₹11,499",4.4
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,2.0,"realme 8i (Space Black, 128 GB)","₹15,999",4.4
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,3.0,"realme 8i (Space Black, 64 GB)","₹13,999",4.5
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,4.0,"realme Narzo 50A (Oxygen Green, 64 GB)","₹11,499",4.4
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,5.0,"realme Narzo 50A (Oxygen Blue, 128 GB)","₹12,499",4.4
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,6.0,"REDMI 9i Sport (Metallic Blue, 64 GB)","₹8,799",4.4
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,7.0,"REDMI 9i Sport (Carbon Black, 64 GB)","₹8,799",4.4
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,8.0,"APPLE iPhone SE (Red, 64 GB)","₹27,999",4.5
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,9.0,"POCO C31 (Shadow Gray, 64 GB)","₹8,999",4.4
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,10.0,"realme C21Y (Cross Black, 32 GB)","₹9,499",4.6
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,11.0,"realme C21Y (Cross Black, 64 GB)","₹10,499",4.5
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,12.0,"realme C21Y (Cross Blue, 64 GB)","₹10,499",4.5
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,13.0,"POCO C31 (Royal Blue, 32 GB)","₹7,999",4.4
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,14.0,"realme C21Y (Cross Blue, 32 GB)","₹9,499",4.6
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,15.0,"APPLE iPhone 12 Mini (Black, 64 GB)","₹38,999",4.5
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,16.0,"MOTOROLA g31 (Baby Blue, 64 GB)","₹12,999",4.3
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,17.0,"APPLE iPhone SE (White, 64 GB)","₹27,999",4.5
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,18.0,"MOTOROLA g31 (Meteorite Grey, 64 GB)","₹12,999",4.3
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,19.0,"realme 8 (Cyber Black, 128 GB)","₹16,999",4.4
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,20.0,"realme 8 (Cyber Silver, 128 GB)","₹17,999",4.4
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,21.0,"realme C11 2021 (Cool Grey, 32 GB)","₹7,499",4.4
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bad,22.0,"realme C11 2021 (Cool Grey, 64 GB)","₹8,999",4.3
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Good,23.0,"realme C11 2021 (Cool Blue, 64 GB)","₹8,999",4.3

# Mean:

In [44]:
# mean it by using "groupby() in data1"


grouped=data1.groupby("state")
grouped.get_group("California").mean()

C:\Users\Tanuja\AppData\Local\Temp/ipykernel_7720/948031170.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  grouped.get_group("California").mean()

sales     361.244
Review      0.500
dtype: float64

In [45]:
# mean it by using "groupby() in data2"


grouped=data2.groupby("Product_rating")
grouped.get_group(4.4).mean()

C:\Users\Tanuja\AppData\Local\Temp/ipykernel_7720/346622123.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  grouped.get_group(4.4).mean()

Index             8.916667
Product_rating    4.400000
Review            0.416667
dtype: float64